require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocmds"

spec "user.mason-and-none-ls"
spec "user.colorscheme"
spec "user.devicons"
spec "user.treesitter"
spec "user.schemastore"
spec "user.lspconfig"
spec "user.telescope"
spec "user.cmp"
spec "user.nvimtree"
spec "user.comment"
spec "user.whichkey"
spec "user.lualine"
spec "user.navic"
spec "user.breadcrumbs"
spec "user.harpoon"
spec "user.illuminate"
spec "user.leap"
spec "user.tokyonight"
spec "user.gitsigns"
spec "user.autopairs"
spec "user.neogit"
spec "user.alpha"
spec "user.project"
spec "user.indentline"
spec "user.toggleterm"

-- spec "user.noice"
-- spec "user.trouble"
-- spec "user.neotest"

spec "user.extras.tabby"
spec "user.extras.neoscroll"
spec "user.extras.oil"
spec "user.extras.ufo"
spec "user.extras.lab"
spec "user.extras.neotab"
spec "user.extras.gitlinker"
spec "user.extras.fidget"
spec "user.extras.bqf"

-- spec "user.extras.tabnine"
-- spec "user.extras.copilot"
require "user.lazy"
